{.$DEFINE TRACEDEBUG}          // save debug log
{.$DEFINE TRACEDEBUG2}        // More extensive logs
{.$DEFINE TRACEDEBUGMEMORY}   // save debug log to memory and only write it to disk on exit.
{.$DEFINE TESTSCALE}          // forces a fake scale value (windows)
{.$DEFINE LIMITRES}           // limits resolution if above 1280 on any axis (android).

{$DEFINE FAKEMOBILE}          // fake several mobile parameters such as a vertical display
{.$DEFINE REZ_360x640}        // Requires FAKEMOBILE
{.$DEFINE REZ_360x740}        // Pixel3 AR
{.$DEFINE REZ_360x780}        // iPhone AR
{.$DEFINE REZ_480x800}        // Galaxy S2
{.$DEFINE REZ_540x960}
{$DEFINE REZ_576x1024}
{.$DEFINE REZ_720x1280}
{.$DEFINE REZ_1080x1920}
{.$DEFINE REZ_1440x2560}
{.$DEFINE REZ_2160x3840}



{.$DEFINE DISPLAYON4K}        // Used high rez testing & screenshots

